#ifndef DUSTPRODLIGHT_GLOBAL_H
#define DUSTPRODLIGHT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DUSTPRODLIGHT_LIBRARY)
#  define DUSTPRODLIGHTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DUSTPRODLIGHTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DUSTPRODLIGHT_GLOBAL_H
